### ISSUE TITLE
Porting to ExpressLRS

### ISSUE THREAD

**Issue by kielerrr** [cmakcay/CRSFv2#1]
Hi, I've also been working on a a solution to send CRSF packets from PC to FC via ExpressLRS. 
Coincidentally, I have been following and building the agilicious and flightmare projects and was inspired to build the ELRS solution by those projects! 

I have the following setup and haven't been able to get packed channel data to the FC with this package yet.
Have you tried porting this to ExpressLRS? 
It seems like it should work with TBS and ELRS.

Sending packed channel data
PC -> TX --> RX -> FC

PC - Python script writing packed channel data to TX serial
TX - Radiomaster Ranger ELRS TX Radio 
RX - BetaFPV ERLS RX 

All devices are flashed to stock firmware except the TX.
On the TX, I modified the firmware to connect to the RX without needing the handset/controller and I set the rx/tx pins on the TX to 3 and 1 which puts the TX's UART on the devices USB port instead of the JR bay connection to the handset. This way the TX shows up as /dev/ttyUSBX and it should respond to packets with dest `\xee`

**Comment by cmakcay** [comment]
Hi, it is interesting to see someone else is working on this! Please note that this script is only to test if the commands can be seen in FC, later I implemented the protocol in Agilicious but I do not know if the authors open sourced CRSF implementation as well, I am not affiliated with the group now. 

I only used TBS but if ELRS uses CRSF v2 protocol as well, I dont see a reason why it should not work. In my setup, I used an FTDI USB to TTL converter cable and directly connected to JR bay port of TX. Here is the configuration:
![configuration](https://github.com/cmakcay/CRSFv2/assets/91556550/0440d6d8-e65d-42ce-a8f5-4db803a203cc)
Unfortunately I do not remember the value of R I used. Without a good choice of R, the signals are corrupted. But as far as I understood, you already separated tx and rx channels to different pins.

I worked with a logic analyzer to see what the radio controller is sending to the TX and reverse engineered it. If you are able to generate the same signal as the radio controller from your PC, the signals should be visible in Betaflight. There is one tricky thing, the arming signal should be sent from the code as well.

I remember that in newer versions of CRSF, there is a more advanced communication going on, which was harder to implement. That is why I used v2, which was already fast and low-latency enough. 

I hope this was helpful, and good luck with the project.

**Comment by kielerrr** [comment]
Thank you for the followup! I understand the RPG team used sbus over a Laird link in the original version of agilicious. Then I think they moved to TBS/CRSF (which of course you would well know!). I assumed they would have moved to ExpressLRS by now with it's active development and F1000Hz rates. 
Unfortunately, when they recently released agilicous, they changed it from open-source to invite only. I applied, and sent a few follow-up inquiries, but never heard back from the RPG team. So, I just have to build the solution independently.
Since ExpressLRS uses CRSF, most of your code will work. I'll modify the parts needed to retrofit it into ExpressLRS. 
I'll send a pull request for fun so you can see the changes

**Comment by DrAlkebsi** [comment]
Hello all.  I have tested this script with slight modifications to the code. I used BetaFPV ELRS mico TX and RX. I was able to transmit data from TX to RX but not reverse.  I have a project where I need to send RC channel data from one PC to another. One thing that took me a while to figure out is that the TX module expects inverted serial data but I was sending the data without using inverter. After passing the data through an inverter ( 74LS04N) I was able to send valid data to the TX module and I could see the RX module light turns solid blue immediately. 

Additionally. since my project does not involve an FC I was not able to test the accuracy of the implementation of the CRC algorithm. Moreover, I had previously written an unpacking function that can decode the channel data sent from the radio handset and tested it. However, when I used the same function to unpack channel data generated and packed by the code in this repo there was a mismatch in the data on channel 5 and above. To the best of my knowledge, the packing function needs to be tested again.   

Overall, Thanks for this repo. It is really useful.
